services:
    goodstarter.oauth.user_provider:
        class:    Affect\MiniCoreBundle\Security\AffectOauthUserProvider
        arguments:
            - @fos_user.user_manager
            - { facebook:  facebookId, instagram: instagramId, twitter: twitterId }
