fos_user_security_login:
    path:  /login
    defaults: { _controller: 'FOSUserBundle:Security:login' }
    methods:  [GET]

fos_user_security_check:
    path:  /login_check
    defaults: { _controller: 'FOSUserBundle:Security:check' }
    methods:  [POST]

fos_user_security_logout:
    path:  /logout
    defaults: { _controller: 'FOSUserBundle:Security:logout' }
    methods:  [GET]


mini_admin_homepage:
    path:  /
    defaults: { _controller: 'MiniWebBundle:Admin/Main:index' }
    methods:  [GET]

mini_admin_user_param_change:
    path:  /
    defaults: { _controller: 'MiniWebBundle:Admin/Main:paramUpdate' }
    methods:  [POST]

mini_admin_user_report:
    path:  /report
    defaults: { _controller: 'MiniWebBundle:Admin/Main:allGenerateReport' }
    methods:  [GET]
