imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/../config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: admin
    user_class:    Affect\MiniCoreBundle\Entity\User
#    group:
#        group_class: Affect\MiniCoreBundle\Entity\Group
    resetting:
        form:
            type:  admin_password_resetting
    profile:
        form:
            type:  admin_profile
    from_email:
        address:        %mailer_user%
        sender_name:    %mailer_user_name%

# HWIOAuthBundle Configuration
hwi_oauth:
    firewall_name:              main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_id%
            client_secret:       %facebook_secret%
            scope:               "email"
            options:
                display:         page
            paths:
                realname:        name
        twitter:
            type:                twitter
            client_id:           %twitter_id%
            client_secret:       %twitter_secret%
            paths:
                realname:        name
#        vkontakte:
#            type:                vkontakte
#            client_id:           %vkontakte_id%
#            client_secret:       %vkontakte_secret%
#            scope:               "email"
#            paths:
#                realname:        [response.0.first_name, response.0.last_name]
        instagram:
            type:                instagram
            client_id:           %instagram_id%
            client_secret:       %instagram_secret%
    fosub:
        username_iterations:    30
        properties:
            facebook:           facebookId
            odnoklassniki:      odnoklassnikiId
            vkontakte:          vkontakteId
            twitter:            twitterId

